spring:
  application:
    name: activity-service

  data:
    mongodb:
      uri: mongodb+srv://wendy:wendy@cluster0.klg5q70.mongodb.net/activities
      database: activities

server:
  port: 8082

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true